{
 "title": "HA SAP HANA  cluster status",
 "description": "HA SAP HANA  cluster status real-time alert dashboard",
 "time": { "from": "2019-10-01T08:18:04.165Z", "to": "2019-10-01T08:38:04.165Z" },
 "templating": {
  "list": [
   { "name": "hanadb_data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "hana_node_name",
    "label": "HANA Node",
    "query": "label_values(node_uname_info, nodename)"
   },
   {
    "name": "hana_node_ip",
    "query": "label_values(node_uname_info{nodename=~\"$hana_node_name\"}, instance)"
   },
   {
    "name": "hana_node_name_1",
    "query": "label_values(node_uname_info{nodename=~\".*1\"}, nodename)"
   },
   {
    "name": "hana_node_name_2",
    "query": "label_values(node_uname_info{nodename=~\".*2\"}, nodename)"
   }
  ]
 },
 "panels": [
  { "title": "HA monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes remote",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"remote\"})"
    }
   ]
  },
  {
   "title": "Nodes shutdown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"shutdown\"})"
    }
   ]
  },
  {
   "title": "Nodes online",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"online\"})"
    }
   ]
  },
  {
   "title": "Resouces configured",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_node_resources{instance=~\"$hana_node_ip:9002\", status=\"active\"})"
    }
   ]
  },
  {
   "title": "Configured nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"expected_up\"})"
    }
   ]
  },
  {
   "title": "Nodes expected up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"expected_up\"})"
    }
   ]
  },
  {
   "title": "Resources failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_node_resources{instance=~\"$hana_node_ip:9002\", status=\"failed\"})"
    }
   ]
  },
  {
   "title": "Nodes on pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"pending\"})"
    }
   ]
  },
  {
   "title": "Nodes on maintenance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"maintenance\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "count(cluster_node_resources{instance=~\"$hana_node_ip:9002\",node=~\".*01\", status=\"active\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "count(cluster_node_resources{instance=~\"$hana_node_ip:9002\", node=~\".*02\", status=\"active\"})"
    }
   ]
  },
  {
   "title": "Resources disabled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_node_resources{instance=~\"$hana_node_ip:9002\", status=\"disabled\"})"
    }
   ]
  },
  {
   "title": "Nodes unclean",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"unclean\"})"
    }
   ]
  },
  {
   "title": "Nodes on standby",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_nodes{instance=~\"$hana_node_ip:9002\", type=\"standby\"})"
    }
   ]
  },
  {
   "title": "Master resources",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_node_resources{instance=~\"$hana_node_ip:9002\", role=\"master\",status=\"active\"})"
    }
   ]
  },
  {
   "title": "Slave resources",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cluster_node_resources{instance=~\"$hana_node_ip:9002\", role=\"slave\", status=\"active\"})"
    }
   ]
  },
  {
   "title": "pacemaker service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\", name=\"pacemaker.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "corosync service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\", name=\"corosync.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "sbd service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\",name=\"sbd.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Quorum votes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "corosync_quorum{instance=~\"$hana_node_ip:9002\",type=\"expected_votes\"}",
     "legendFormat": "expected_votes"
    },
    {
     "expr": "corosync_quorum{instance=~\"$hana_node_ip:9002\",type=\"highest_expected\"}",
     "legendFormat": "highest_expected_votes"
    },
    {
     "expr": "corosync_quorum{instance=~\"$hana_node_ip:9002\", type=\"total_votes\"}",
     "legendFormat": "total votes"
    },
    {
     "expr": "corosync_quorum{instance=~\"$hana_node_ip:9002\", type=\"quorum\"}",
     "legendFormat": "quorum"
    }
   ]
  },
  {
   "title": "Corosync Ring  errors total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "corosync_ring_errors_total{instance=~\"$hana_node_ip:9002\"}"
    }
   ]
  },
  {
   "title": "hanadb_exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\",name=\"hanadb_exporter@prd_00.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "ha_cluster exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\",name=\"prometheus-ha_cluster_exporter.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "node exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\",name=\"prometheus-node_exporter.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "hawk  service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\", name=\"hawk.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "hawk  service backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=~\"$hana_node_ip:9100\", name=\"hawk-backend.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Cluster quorate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "corosync_quorate{instance=~\"$hana_node_ip:9002\"}"
    }
   ]
  }
 ]
}