{
 "title": "SAP HANA Dashboard",
 "description": "SAP HANA Database Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hanadb_data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "hana_node",
    "label": "HANA Node",
    "query": "label_values(hanadb_host_memory_physical_total_mb, host)"
   }
  ]
 },
 "panels": [
  { "title": "SAP HANA Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HANA Memory Stack",
   "type": "graph",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_host_memory_physical_total_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Total Physical Memory"
    },
    {
     "expr": "hanadb_host_memory_physical_free_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Free Physical Memory"
    },
    {
     "expr": "hanadb_host_memory_resident_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Resident Memory "
    },
    {
     "expr": "hanadb_host_memory_alloc_limit_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Allocation Limit"
    },
    {
     "expr": "hanadb_host_memory_pool_size_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "hanadb_host_memory_used_total_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Used Pool"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Average percent of CPU usage based on usage type.",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(hanadb_cpu_busy_percent{host=~\"$hana_node\"})",
     "legendFormat": "% Busy Time"
    },
    {
     "expr": "avg(hanadb_cpu_system_percent{host=~\"$hana_node\"})",
     "legendFormat": "% System Time"
    },
    {
     "expr": "avg(hanadb_cpu_idle_percent{host=~\"$hana_node\"})",
     "legendFormat": "% Idle Time"
    },
    {
     "expr": "avg(hanadb_cpu_user_percent{host=~\"$hana_node\"})",
     "legendFormat": "% User Time"
    },
    {
     "expr": "avg(hanadb_cpu_waitio_percent{host=~\"$hana_node\"})",
     "legendFormat": "% Wait I/O"
    }
   ]
  },
  {
   "title": "Used RAM x Allocation Limit",
   "type": "singlestat",
   "description": "Percent of Total Used RAM Memory compared to the HANA Allocation Limit value.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hanadb_host_memory_used_total_mb{host=~\"$hana_node\"}) / sum(hanadb_host_memory_alloc_limit_mb{host=~\"$hana_node\"}) * 100",
     "legendFormat": "Percent of Total Used Memory"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_connections_total_count{host=~\"$hana_node\"}",
     "legendFormat": "{{connection_type}} : {{connection_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "description": "Disk usage based on usage type.",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "expr": "hanadb_disk_used_size_mb{host=~\"$hana_node\"} + 0",
     "legendFormat": "Used Disk"
    },
    {
     "expr": "hanadb_disk_total_size_mb{host=~\"$hana_node\"} + 0",
     "legendFormat": "Disk Total Size"
    },
    {
     "expr": "((hanadb_disk_used_size_mb{host=~\"$hana_node\"} / hanadb_disk_total_size_mb{host=~\"$hana_node\"}) * 100) ",
     "legendFormat": "Percent Used"
    },
    {
     "expr": "hanadb_disk_total_device_size_mb {host=~\"$hana_node\"} ",
     "legendFormat": "Total Device Size"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Sum of the CPU busy time of all cores of all hosts.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(hanadb_cpu_busy_percent{host=~\"$hana_node\"})"
    }
   ]
  },
  {
   "title": "Number of Cores",
   "type": "singlestat",
   "description": "Total Number of CPU Cores",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (count by (core) (hanadb_cpu_busy_percent{host=~\"$hana_node\"}))"
    }
   ]
  },
  {
   "title": "Total Physical RAM Memory",
   "type": "singlestat",
   "description": "Total Physical RAM Memory available on the host.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_physical_total_mb{host=~\"$hana_node\"}/1024"
    }
   ]
  },
  {
   "title": "Allocation Limit",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 25 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_alloc_limit_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Allocation Limit"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 25 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_used_total_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 25 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_shared_alloc_mb{host=\"$hana_node\"} / 1024",
     "legendFormat": "Allocated Shared Memory"
    }
   ]
  },
  {
   "title": "Memory Used Peak",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 25 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_used_peak_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Memory Used Peak"
    }
   ]
  },
  {
   "title": "Memory Code Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 25 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_code_size_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Code Size"
    }
   ]
  },
  {
   "title": "Used Swap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 25 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_swap_used_mb{host=~\"$hana_node\"} / 1024",
     "legendFormat": "Used Swap"
    }
   ]
  },
  {
   "title": "CS Tables Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_column_tables_used_memory_mb{host=~\"$hana_node\"}"
    }
   ]
  },
  { "title": "SAP HANA Administration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory used by Service",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_memory_service_total_used_mb{host=~\"$hana_node\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "SQL Executions Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_service_executions_count{host=~\"$hana_node\"} + 0)"
    },
    {
     "expr": "hanadb_sql_service_elapsed_time_ms{host=~\"$hana_node\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_elap_per_exec_avg_ms{host=~\"$hana_node\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_lock_per_exec_ms{host=~\"$hana_node\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_max_ela_time_ms{host=~\"$hana_node\"} + 0"
    }
   ]
  },
  {
   "title": "Top SQL Time Consumers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_top_time_consumers_mu{host=~\"$hana_node\"} + 0)"
    },
    {
     "expr": "hanadb_sql_top_time_consumers_count{host=~\"$hana_node\"} + 0"
    }
   ]
  },
  {
   "title": "Used Memory by Schema",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sort(sum(hanadb_schema_used_memory_mb{host=~\"$hana_node\"}) by (schema_name))",
     "legendFormat": "{{schema_name}}"
    }
   ]
  },
  {
   "title": "Top SQL Memory Consumers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_top_mem_consumers_byte{host=~\"$hana_node\"} + 0)"
    },
    {
     "expr": "sort(hanadb_sql_top_mem_consumers_count{host=~\"$hana_node\"} + 0)"
    }
   ]
  },
  {
   "title": "TOP CS Tables Memory Consumers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sort(hanadb_table_cs_top_mem_total_mb{host=~\"$hana_node\"}) + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_estimated_max_mb{host=~\"$hana_node\"} + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_disk_size_mb{host=~\"$hana_node\"} + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_record_count{host=~\"$hana_node\"} + 0"
    }
   ]
  },
  {
   "title": "DATA Files Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "hanadb_disk_data_files_used_size_mb{host=~\"$hana_node\"} + 0"
    },
    {
     "expr": "hanadb_disk_data_files_total_size_mb{host=~\"$hana_node\"} + 0"
    },
    {
     "expr": "(hanadb_disk_data_files_used_size_mb{host=~\"$hana_node\"} / hanadb_disk_data_files_total_size_mb{host=~\"$hana_node\"}) * 100"
    }
   ]
  },
  { "title": "SAP HANA System Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "HANA System Replication Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "hanadb_sr_replication_status + 0"
    },
    {
     "expr": "hanadb_sr_secondary_active_status + 0"
    },
    {
     "expr": "hanadb_sr_secondary_reconnect_count + 0"
    },
    {
     "expr": "hanadb_sr_secondary_failover_count + 0"
    }
   ]
  },
  {
   "title": "System Replication Log Shipping Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hanadb_sr_ship_delay_seconds",
     "legendFormat": "{{host}}:{{port}} -> {{secondary_host}}:{{secondary_port}}"
    }
   ]
  },
  {
   "title": "System Replication Used Async Log Shipping Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_sr_async_used_shipping_buffer_mb",
     "legendFormat": "{{host}}:{{port}} -> {{secondary_host}}:{{secondary_port}}"
    }
   ]
  },
  {
   "title": "System Replication Takeover History",
   "type": "table",
   "description": "System Replication Takeover history. When the values of end time cannot be collected, the duration time is presented as -1 and the end time as \"N/A\"",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "hanadb_sr_takeover_replication_status + 0"
    },
    {
     "expr": "hanadb_sr_takeover_duration_time_seconds + 0"
    },
    {
     "expr": "hanadb_sr_takeover_log_position_bigint + 0"
    },
    {
     "expr": "hanadb_sr_takeover_shipped_log_position_bigint + 0"
    }
   ]
  },
  {
   "title": "SAP HANA Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Rate (KB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "hanadb_network_receive_rate_kb_per_seconds{host=~\"$hana_node\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Transmission Rate (KB/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "hanadb_network_transmission_rate_kb_per_seconds{host=~\"$hana_node\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Receive/Transmission Errors per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hanadb_network_receive_rate_errors_per_seconds{host=~\"$hana_node\"}",
       "legendFormat": "{{interface}} - Rec. rate"
      },
      {
       "expr": "hanadb_network_transmission_rate_errors_per_seconds{host=~\"$hana_node\"}",
       "legendFormat": "{{interface}} - Trans. rate"
      }
     ]
    },
    {
     "title": "Received Requests per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hanadb_network_receive_requests_per_seconds{host=~\"$hana_node\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Transmitted Requests per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hanadb_network_transmission_rate_requests_per_seconds{host=~\"$hana_node\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Collisions per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hanadb_network_collisions_per_seconds{host=~\"$hana_node\"}",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SAP HANA Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "I/O Throughput",
     "type": "graph",
     "description": "I/O Throughput  per Disk in KB/Sec",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "hanadb_disk_io_throughput_kb_second{host=~\"$hana_node\"}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "description": "I/O Latency in miliseconds.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hanadb_disk_io_latency_ms{host=~\"$hana_node\"}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "I/O Service Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hanadb_disk_io_service_time_ms{host=~\"$hana_node\"}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Requests per Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "hanadb_disk_io_requests_per_second{host=~\"$hana_node\"}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Queue Length (Number of Requests)",
     "type": "graph",
     "description": "average queue length of the requests that were issued to the Disk Device",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "hanadb_disk_io_queue_length_requests{host=~\"$hana_node\"}",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "I/O Wait Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "hanadb_disk_io_wait_time_ms{host=~\"$hana_node\"}",
       "legendFormat": "{{disk}}"
      }
     ]
    }
   ]
  }
 ]
}