{
 "title": "Multi-Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Nodes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{instance=~\".*:9100\"} == 1) by (job) / count(up{instance=~\".*:9100\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg Cluster Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])) by (job) + avg(irate(node_network_receive_bytes_total{device!=\"lo\"}[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg Cluster Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{instance=~\".*:9100\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg Cluster CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg (sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance, job, cpu)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg Cluster Storage Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(1 - node_filesystem_avail_bytes{device=~\"/dev.+\"} / node_filesystem_size_bytes{device=~\"/dev.+\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Pacemaker & Corosync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Online Pacemaker nodes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(count(ha_cluster_pacemaker_nodes) by (node,job)) by (job) / count(up{instance=~\".*:9002\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active resources",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "min(count(ha_cluster_pacemaker_resources{status=\"active\"}) by (job,instance))  by (job) / max(count(ha_cluster_pacemaker_resources) by (job,instance)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Online nodes over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(ha_cluster_pacemaker_nodes{status=\"online\"}) by (node,job)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active resources over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(count(ha_cluster_pacemaker_resources{status=\"active\"}) by (job,instance))  by (job) / max(count(ha_cluster_pacemaker_resources) by (job,instance)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}