{
 "title": "SAP NetWeaver Details",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Start Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sap_start_service_processes == 1)",
     "legendFormat": "GRAY"
    },
    {
     "expr": "count(sap_start_service_processes == 2)",
     "legendFormat": "GREEN"
    },
    {
     "expr": "count(sap_start_service_processes == 3)",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "count(sap_start_service_processes == 4)",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "Process List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sap_start_service_processes" }
   ]
  },
  { "title": "Enqueue Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Lock Table Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sap_enqueue_server_locks_now", "legendFormat": "Locks" },
    { "expr": "sap_enqueue_server_owner_now", "legendFormat": "Lock owners" },
    {
     "expr": "sap_enqueue_server_arguments_now",
     "legendFormat": "Lock arguments"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sap_enqueue_server_enqueue_requests",
     "legendFormat": "Lock"
    },
    {
     "expr": "sap_enqueue_server_enqueue_rejects",
     "legendFormat": "Rejected"
    },
    {
     "expr": "sap_enqueue_server_dequeue_requests",
     "legendFormat": "Release"
    },
    {
     "expr": "sap_enqueue_server_dequeue_all_requests",
     "legendFormat": "LUW release"
    },
    {
     "expr": "sap_enqueue_server_cleanup_requests",
     "legendFormat": "Server release"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sap_enqueue_server_enqueue_errors",
     "legendFormat": "Lock"
    },
    {
     "expr": "sap_enqueue_server_dequeue_errors",
     "legendFormat": "Release"
    }
   ]
  },
  { "title": "Work Process Dispatcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Dispatcher Queue Depth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sap_dispatcher_queue_now", "legendFormat": "{{type}} {{instance}}" }
   ]
  },
  {
   "title": "Dispatcher Queue Depth High",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 19 },
   "targets": [
    { "expr": "sap_dispatcher_queue_high", "legendFormat": "{{type}} {{instance}}" }
   ]
  },
  {
   "title": "Dispatcher Queue Depth Threshold",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 19 },
   "targets": [
    { "expr": "sap_dispatcher_queue_max", "legendFormat": "{{type}} {{instance}}" }
   ]
  },
  {
   "title": "Dispatcher Queues Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sap_dispatcher_queue_reads", "legendFormat": "{{type}} {{instance}}" }
   ]
  },
  {
   "title": "Dispatcher Queue Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sap_dispatcher_queue_writes", "legendFormat": "{{type}} {{instance}}" }
   ]
  }
 ]
}