{
 "title": "Multi-Cluster Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Nodes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{instance=~\".*:9100\"} == 1) by (job) / count(up{instance=~\".*:9100\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance, cpu)) by (instance) + on(instance) group_left(nodename) (0 * node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) by (instance) + on(instance) group_left(nodename) (0 * node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Up Nodes over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{instance=~\".*:9100\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])) by (instance) + avg(irate(node_network_receive_bytes_total{device!=\"lo\"}[5m])) by (instance)) + on(instance) group_left(nodename) (0 * node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Node Storage Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(avg(1 - node_filesystem_avail_bytes{device=~\"/dev.+\"} / node_filesystem_size_bytes{device=~\"/dev.+\"}) by (instance,device)) + on(instance) group_left(nodename) (0 * node_uname_info)",
     "legendFormat": "{{nodename}} {{device}}"
    }
   ]
  },
  { "title": "Pacemaker & Corosync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Online Pacemaker Nodes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(count(ha_cluster_pacemaker_nodes{status=\"online\"} == 1) by (job,node)) by (job) / count(count(ha_cluster_pacemaker_nodes) by (job,node)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Resources",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "count(count(ha_cluster_pacemaker_resources{status=\"active\"} == 1) by (resource,node,job)) by (job) / count(count(ha_cluster_pacemaker_resources) by (resource,job,node)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Healthy SBD Devices",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "count(ha_cluster_sbd_devices{status=\"healthy\"}) by (job) / count(ha_cluster_sbd_devices) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Corosync Quorate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "count(ha_cluster_corosync_quorate == 1) by (job) / count(ha_cluster_corosync_quorate) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Online Pacemaker Nodes over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(ha_cluster_pacemaker_nodes{status=\"online\"} == 1) by (node,job)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Resources per Node over time ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(ha_cluster_pacemaker_resources{status=\"active\"} == 1) by (resource,node,job)) by (job,node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Healthy SBD devices over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ha_cluster_sbd_devices{status=\"healthy\"}) by (job) / count(count(ha_cluster_sbd_devices) by (instance,job)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Corosync Quorate over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ha_cluster_corosync_quorate) by (job) / count(ha_cluster_corosync_quorate) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}