{
 "title": "SAP HANA Details",
 "description": "SAP HANA Details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node_name",
    "label": "Node",
    "query": "label_values(hanadb_host_memory_used_total_mb, host)"
   },
   {
    "name": "node_ip",
    "query": "label_values(node_uname_info{nodename=\"$node_name\"}, instance)"
   },
   {
    "name": "sid",
    "label": "SID",
    "query": "label_values(hanadb_host_memory_used_total_mb{host=\"$node_name\"}, sid)"
   },
   {
    "name": "instance_number",
    "label": "Instance number",
    "query": "label_values(hanadb_host_memory_used_total_mb{host=\"$node_name\", sid=\"$sid\"}, insnr)"
   },
   {
    "name": "database_name",
    "label": "Database",
    "query": "label_values(hanadb_host_memory_used_total_mb{host=\"$node_name\", sid=\"$sid\", insnr=\"$instance_number\"}, database_name)"
   }
  ]
 },
 "panels": [
  { "title": "HANA Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HANA Database Alerts",
   "type": "table",
   "description": "Alerts raised from the HANA database internal alerting system",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) "
    }
   ]
  },
  { "title": "SAP HANA Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HANA Memory Stack",
   "type": "graph",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_host_memory_physical_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Total Physical Memory"
    },
    {
     "expr": "hanadb_host_memory_physical_free_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Free Physical Memory"
    },
    {
     "expr": "hanadb_host_memory_resident_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Resident Memory "
    },
    {
     "expr": "hanadb_host_memory_alloc_limit_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Allocation Limit"
    },
    {
     "expr": "hanadb_host_memory_pool_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "hanadb_host_memory_used_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Used Pool"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Average percent of CPU usage based on usage type.",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(hanadb_cpu_busy_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% Busy Time"
    },
    {
     "expr": "avg(hanadb_cpu_system_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% System Time"
    },
    {
     "expr": "avg(hanadb_cpu_idle_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% Idle Time"
    },
    {
     "expr": "avg(hanadb_cpu_user_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% User Time"
    },
    {
     "expr": "avg(hanadb_cpu_waitio_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% Wait I/O"
    }
   ]
  },
  {
   "title": "Used RAM x Allocation Limit",
   "type": "singlestat",
   "description": "Percent of Total Used RAM Memory compared to the HANA Allocation Limit value.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hanadb_host_memory_used_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) / sum(hanadb_host_memory_alloc_limit_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) * 100",
     "legendFormat": "Percent of Total Used Memory"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_connections_total_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{connection_type}} : {{connection_status}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "description": "System-wide filesystem statistics",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 26 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"^$node_ip:\\\\d+$\", fstype!=\"tmpfs\"} - node_filesystem_avail_bytes",
     "legendFormat": "Used Disk"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"^$node_ip:\\\\d+$\", fstype!=\"tmpfs\"}",
     "legendFormat": "Disk Total Size"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"^$node_ip:\\\\d+$\", fstype!=\"tmpfs\"} - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100",
     "legendFormat": "Percent Used"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Sum of the CPU busy time of all cores of all hosts.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(hanadb_cpu_busy_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})"
    }
   ]
  },
  {
   "title": "HANA filesystem usage",
   "type": "table",
   "description": "Details HANA on how HANA uses the filesystem in its various directories",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 31 },
   "targets": [
    {
     "expr": "hanadb_disk_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0",
     "legendFormat": "Used Disk"
    },
    {
     "expr": "hanadb_disk_total_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0",
     "legendFormat": "Disk Total Size"
    },
    {
     "expr": "(hanadb_disk_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / hanadb_disk_total_size_mb) * 100",
     "legendFormat": "Percent Used"
    },
    {
     "expr": "hanadb_disk_total_device_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "Total Device Size"
    }
   ]
  },
  {
   "title": "Number of Cores",
   "type": "singlestat",
   "description": "Total Number of CPU Cores",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (count by (core) (hanadb_cpu_busy_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}))"
    }
   ]
  },
  {
   "title": "Total Physical RAM Memory",
   "type": "singlestat",
   "description": "Total Physical RAM Memory available on the host.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 37 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_physical_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}/1024"
    }
   ]
  },
  {
   "title": "Allocation Limit",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 37 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_alloc_limit_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Allocation Limit"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 37 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_used_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 37 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_shared_alloc_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Allocated Shared Memory"
    }
   ]
  },
  {
   "title": "Memory Used Peak",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 37 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_used_peak_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Memory Used Peak"
    }
   ]
  },
  {
   "title": "Memory Code Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 37 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_code_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Code Size"
    }
   ]
  },
  {
   "title": "Used Swap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 37 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_host_memory_swap_used_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Used Swap"
    }
   ]
  },
  {
   "title": "CS Tables Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hanadb_column_tables_used_memory_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}"
    }
   ]
  },
  { "title": "SAP HANA Administration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Memory used by Service",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_memory_service_total_used_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "SQL Executions Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_service_executions_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    },
    {
     "expr": "hanadb_sql_service_elapsed_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_elap_per_exec_avg_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_lock_per_exec_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_max_ela_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "Top SQL Time Consumers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_top_time_consumers_mu{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    },
    {
     "expr": "hanadb_sql_top_time_consumers_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "Used Memory by Schema",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sort(sum(hanadb_schema_used_memory_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) by (schema_name))",
     "legendFormat": "{{schema_name}}"
    }
   ]
  },
  {
   "title": "Top SQL Memory Consumers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_top_mem_consumers_byte{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    },
    {
     "expr": "sort(hanadb_sql_top_mem_consumers_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    }
   ]
  },
  {
   "title": "TOP CS Tables Memory Consumers",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sort(hanadb_table_cs_top_mem_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_estimated_max_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_disk_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_record_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "DATA Files Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "hanadb_disk_data_files_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_disk_data_files_total_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "(hanadb_disk_data_files_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / hanadb_disk_data_files_total_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) * 100"
    }
   ]
  },
  { "title": "SAP HANA System Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "HANA System Replication Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "hanadb_sr_replication_status{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_secondary_active_status{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_secondary_reconnect_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_secondary_failover_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "System Replication Log Shipping Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hanadb_sr_ship_delay_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{host}}:{{port}} -> {{secondary_host}}:{{secondary_port}}"
    }
   ]
  },
  {
   "title": "System Replication Used Async Log Shipping Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_sr_async_used_shipping_buffer_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{host}}:{{port}} -> {{secondary_host}}:{{secondary_port}}"
    }
   ]
  },
  {
   "title": "System Replication Takeover History",
   "type": "table",
   "description": "System Replication Takeover history. When the values of end time cannot be collected, the duration time is presented as -1 and the end time as \"N/A\"",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "hanadb_sr_takeover_replication_status{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_takeover_duration_time_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_takeover_log_position_bigint{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_takeover_shipped_log_position_bigint{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  { "title": "SAP HANA Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Receive Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_receive_rate_kb_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Transmission Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_transmission_rate_kb_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Receive/Transmission Errors per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_receive_rate_errors_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}} - Rec. rate"
    },
    {
     "expr": "hanadb_network_transmission_rate_errors_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}} - Trans. rate"
    }
   ]
  },
  {
   "title": "Received Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_receive_requests_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Transmitted Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_transmission_rate_requests_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Collisions per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_collisions_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "SAP HANA Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "I/O Throughput",
   "type": "graph",
   "description": "I/O Throughput  per Disk in KB/Sec",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_throughput_kb_second{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "I/O Latency in miliseconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 119 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_latency_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "I/O Service Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 119 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_service_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Requests per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_requests_per_second{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Queue Length (Number of Requests)",
   "type": "graph",
   "description": "average queue length of the requests that were issued to the Disk Device",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 128 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_queue_length_requests{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 128 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_wait_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}