# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090/
  basicAuth: False
  isDefault: True
  editable: true
  jsonData:
    timeInterval: 5s
