# Libvirt related variables

variable "qemu_uri" {
  description = "URI to connect with the qemu-service."
  default     = "qemu:///system"
}

variable "storage_pool" {
  description = "libvirt storage pool name for VM disks"
  default     = "default"
}

variable "network_name" {
  description = "Already existing virtual network name. If it's not provided a new one will be created"
  type        = string
  default     = ""
}

variable "iprange" {
  description = "IP range of the isolated network (it must be provided even when the network_name is given, due terraform-libvirt-provider limitations we cannot get the current network data)"
  type        = string
}

variable "isolated_network_bridge" {
  description = "A name for the isolated virtual network bridge device. It must be no longer than 15 characters. Leave empty to have it auto-generated by libvirt."
  type        = string
  default     = ""
}

variable "base_source_image" {
  description = "qcow2 image used to create the generic base image"
  type        = string
  default     = ""
}

variable "base_image_name" {
  description = "Already existing volume name in the same storage pool with a sles4sap image that will be used (specific nodes images will have preference over this image). It's only used if base_source_image is not provided"
  type        = string
  default     = ""
}

# Deployment variables

variable "reg_code" {
  description = "If informed, register the product using SUSEConnect"
  default     = ""
}

variable "reg_email" {
  description = "Email used for the registration"
  default     = ""
}

# The module format must follow SUSEConnect convention:
# <module_name>/<product_version>/<architecture>
# Example: Suggested modules for SLES for SAP 15
# - sle-module-basesystem/15/x86_64
# - sle-module-desktop-applications/15/x86_64
# - sle-module-server-applications/15/x86_64
# - sle-ha/15/x86_64 (Need the same regcode as SLES for SAP)
# - sle-module-sap-applications/15/x86_64
variable "reg_additional_modules" {
  description = "Map of the modules to be registered. Module name = Regcode, when needed."
  type        = map(string)
  default     = {}
}

# Repository url used to install HA/SAP deployment packages"
# The latest RPM packages can be found at:
# https://download.opensuse.org/repositories/network:/ha-clustering:/Factory/{YOUR OS VERSION}
# Contains the salt formulas rpm packages.
variable "ha_sap_deployment_repo" {
  description = "Repository url used to install HA/SAP deployment packages. If SLE version is not set, the deployment will automatically detect the current OS version"
  type        = string
}

variable "devel_mode" {
  description = "Increase ha_sap_deployment_repo repository priority to get the packages from this repository instead of SLE official channels"
  type        = bool
  default     = false
}

variable "provisioner" {
  description = "Used provisioner option. Available options: salt. Let empty to not use any provisioner"
  default     = "salt"
}

variable "background" {
  description = "Run the provisioner execution in background if set to true finishing terraform execution"
  type        = bool
  default     = false
}

# Hana related variables

variable "hana_count" {
  description = "Number of hana nodes"
  type        = number
  default     = 2
}

variable "hana_source_image" {
  description = "qcow2 image used to create the hana image"
  type        = string
  default     = ""
}

variable "hana_image_name" {
  description = "Already existing volume name in the same storage pool with a sles4sap image that will be used. It's only used if hana_source_image is not provided"
  type        = string
  default     = ""
}

variable "hana_inst_media" {
  description = "URL of the NFS share where the SAP HANA software installer is stored. This media shall be mounted in `hana_inst_folder`"
  type        = string
}

variable "hana_inst_folder" {
  description = "Folder where SAP HANA installation files are mounted"
  type        = string
  default     = "/sapmedia/HANA"
}

variable "hana_platform_folder" {
  description = "Path to the hana platform media, relative to the 'hana_inst_media' mounting point"
  type        = string
  default     = ""
}

variable "hana_sapcar_exe" {
  description = "Path to the sapcar executable, relative to the 'hana_inst_media' mounting point"
  type        = string
  default     = ""
}

variable "hdbserver_sar" {
  description = "Path to the HANA database server installation sar archive, relative to the 'hana_inst_media' mounting point"
  type        = string
  default     = ""
}

variable "hana_extract_dir" {
  description = "Absolute path to folder where SAP HANA sar archive will be extracted"
  type        = string
  default     = "/sapmedia/HANA"
}

variable "hana_fstype" {
  description = "Filesystem type to use for HANA"
  type        = string
  default     = "xfs"
}

variable "host_ips" {
  description = "IP addresses of the hana nodes"
  type        = list(string)
  default     = []
}

variable "hana_cluster_vip" {
  description = "IP address used to configure the hana cluster floating IP. It must be in other subnet than the machines!"
  type        = string
  default     = ""
}

variable "scenario_type" {
  description = "Deployed scenario type. Available options: performance-optimized, cost-optimized"
  default     = "performance-optimized"
}

# Iscsi server related variables

variable "shared_storage_type" {
  description = "Used shared storage type for fencing (sbd). Available options: iscsi, shared-disk."
  type        = string
  default     = "iscsi"
}

variable "iscsi_source_image" {
  description = "qcow2 image used to create the iscsi image"
  type        = string
  default     = ""
}

variable "iscsi_image_name" {
  description = "Already existing volume name in the same storage pool with a sles4sap image that will be used. It's only used if iscsi_source_image is not provided"
  type        = string
  default     = ""
}

variable "iscsi_srv_ip" {
  description = "iscsi server address (only used if shared_storage_type is iscsi)"
  type        = string
  default     = ""
}

variable "iscsi_disks" {
  description = "Number of partitions attach to iscsi server. 0 means `all`."
  default     = 0
}

# Monitoring related variables

variable "monitoring_enabled" {
  description = "Enable the host to be monitored by exporters, e.g node_exporter"
  type        = bool
  default     = false
}

variable "monitoring_source_image" {
  description = "qcow2 image used to create the monitoring image"
  type        = string
  default     = ""
}

variable "monitoring_image_name" {
  description = "Already existing volume name in the same storage pool with a sles4sap image that will be used. It's only used if monitoring_source_image is not provided"
  type        = string
  default     = ""
}

variable "monitoring_srv_ip" {
  description = "Monitoring server address"
  type        = string
  default     = ""
}

# Netweaver related variables

variable "netweaver_enabled" {
  description = "Enable SAP Netweaver deployment"
  type        = bool
  default     = false
}

variable "netweaver_source_image" {
  description = "qcow2 image used to create the netweaver image"
  type        = string
  default     = ""
}

variable "netweaver_image_name" {
  description = "Already existing volume name in the same storage pool with a sles4sap image that will be used. It's only used if netweaver_source_image is not provided"
  type        = string
  default     = ""
}

variable "netweaver_ips" {
  description = "IP addresses of the netweaver nodes"
  type        = list(string)
  default     = []
}

variable "netweaver_virtual_ips" {
  description = "IP addresses of the netweaver nodes"
  type        = list(string)
  default     = []
}

variable "netweaver_nfs_share" {
  description = "URL of the NFS share where /sapmnt and /usr/sap/{sid}/SYS will be mounted. This folder must have the sapmnt and usrsapsys folders"
  type        = string
  default     = ""
}

variable "netweaver_product_id" {
  description = "Netweaver installation product. Even though the module is about Netweaver, it can be used to install other SAP instances like S4/HANA"
  type        = string
  default     = "NW750.HDB.ABAPHA"
}

variable "netweaver_inst_media" {
  description = "URL of the NFS share where the SAP Netweaver software installer is stored. This media shall be mounted in `/sapmedia/NW`"
  type        = string
  default     = ""
}

variable "netweaver_swpm_folder" {
  description = "Netweaver software SWPM folder, path relative from the `netweaver_inst_media` mounted point"
  type        = string
  default     = ""
}

variable "netweaver_sapcar_exe" {
  description = "Path to sapcar executable, relative from the `netweaver_inst_media` mounted point"
  type        = string
  default     = ""
}

variable "netweaver_swpm_sar" {
  description = "SWPM installer sar archive containing the installer, path relative from the `netweaver_inst_media` mounted point"
  type        = string
  default     = ""
}

variable "netweaver_swpm_extract_dir" {
  description = "Extraction path for Netweaver software SWPM folder, if SWPM sar file is provided"
  type        = string
  default     = "/sapmedia/NW/SWPM"
}

variable "netweaver_sapexe_folder" {
  description = "Software folder where needed sapexe `SAR` executables are stored (sapexe, sapexedb, saphostagent), path relative from the `netweaver_inst_media` mounted point"
  type        = string
  default     = ""
}

variable "netweaver_additional_dvds" {
  description = "Software folder with additional SAP software needed to install netweaver (NW export folder and HANA HDB client for example), path relative from the `netweaver_inst_media` mounted point"
  type        = list
  default     = []
}

# DRBD related variables

variable "drbd_enabled" {
  description = "Enable the drbd cluster for nfs"
  type        = bool
  default     = false
}

variable "drbd_source_image" {
  description = "qcow2 image used to create the drbd image"
  type        = string
  default     = ""
}

variable "drbd_image_name" {
  description = "Already existing volume name in the same storage pool with a sles4sap image that will be used. It's only used if drbd_source_image is not provided"
  type        = string
  default     = ""
}

variable "drbd_count" {
  description = "Number of drbd machines to create the cluster"
  default     = 2
}

variable "drbd_ips" {
  description = "IP addresses of the drbd nodes"
  type        = list(string)
  default     = []
}

variable "drbd_cluster_vip" {
  description = "IP address used to configure the drbd cluster floating IP. It must be in other subnet than the machines!"
  type        = string
  default     = ""
}

variable "drbd_shared_storage_type" {
  description = "Used shared storage type for fencing (sbd) for drbd cluster. Available options: iscsi, shared-disk."
  type        = string
  default     = "iscsi"
}

# Specific QA variables

variable "qa_mode" {
  description = "Enable test/qa mode (disable extra packages usage not coming in the image)"
  type        = bool
  default     = false
}

variable "hwcct" {
  description = "Execute HANA Hardware Configuration Check Tool to bench filesystems"
  type        = bool
  default     = false
}

# Pre deployment

variable "pre_deployment" {
  description = "Enable pre deployment local execution. Only available for clients running Linux"
  type        = bool
  default     = false
}
